# Generated by Django 5.0.7 on 2025-07-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seithi', '0006_magazine_magazinesubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
