# Generated by Django 5.0.7 on 2025-07-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seithi', '0007_alter_magazine_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seithi.magazine')),
            ],
        ),
    ]
